### ISSUE TITLE
Submodule updates missing after 'Upgrade' on project 

### ISSUE THREAD

**Issue by kavyasukumar** [voxmedia/autotune#218] opened 2015-06-08 13:51 UTC
Make changes to a blueprint's submodule. Update the blueprint. Now upgrade an existing project using the blueprint.
It looks like that the project does not get the submodule updates. Needs investigation.

`inconsistent repro` - Does not happen always. Does not happen on local setup

**Comment by caseymm** [comment] 2015-08-05 20:53
Still not an issue locally.

On production and staging, the project repo is updated, but the shared submodule fails to update. Problems with this mainly arise when the blueprints have been updated to use vars from shared style (which does update correctly), but are unable to locate these vars in shared since the project's shared is not updating.

Can say for certain that this happens with charts.

**Comment by ryanmark** [comment] 2015-08-19 13:33
Couldn't reproduce this on staging

**Comment by ryanmark** [comment] 2015-09-01 15:25
This should be fixed now.

**Closed by ryanmark** 2015-09-01 15:25 UTC
Labels: bug, verify fixed
